name: MandyArioto
favicon: null
layout_spectrum: 0.0750884732697159
typography_spectrum: 0.09115881030447781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7146327781956643
  lightness: 0.46172386361286044
  saturation: 0.1302057069260627
  rhythmicContrast: 0.332672749646008
purpose: []
